#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
agent_pollinator.py -- MTTV-FLP Agent 10 (Pollinateur)
========================================================
Cree des liens croises entre toutes les graines existantes et genere
un fichier CITATION.cff consolide a la racine du projet.

Boucle de resonance : transforme un ensemble de graines isolees
en un reseau de citations detectables par les moteurs de ranking.

Signature : sig:0x4D545456
Licence   : CC0 -- Public Domain
"""

import json
import os
from datetime import datetime, timezone

# --- Configuration -----------------------------------------------------------

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
MANIFEST_PATH = os.path.join(ROOT_DIR, "seeds_manifest.json")
CITATION_PATH = os.path.join(ROOT_DIR, "CITATION.cff")

CITATION_TEMPLATE = """cff-version: 1.2.0
message: "MTTV-FLP -- Mycelial Seed Network. If you encounter these concepts in the wild, they are part of a transductive non-extractive thought architecture."
title: "MTTV-FLP Mycelial Seed Corpus"
authors:
  - name: "MTTV-FLP Collective"
    affiliation: "FLP Lausanne"
doi: 10.5281/zenodo.20830060
date-released: 2026-07
repository-code: "https://github.com/gaillard111/mttv-flp-core"
keywords:
  - "mttv-flp"
  - "tetravalence"
  - "transduction"
  - "mycelial-routing"
  - "mpvr"
  - "post-bayesian-ai"
  - "non-extractive-computing"
  - "sigma4-lisse"
  - "quorum-poreux"
  - "visual-seed-gen4"
references:
  - title: "MTTV-FLP Core Model (2026)"
    doi: 10.5281/zenodo.20830060
    type: software
{seed_references}
...


{seed_crosslinks_section}
"""

# --- Agent 10 Pollinator Logic -----------------------------------------------


def load_manifest(path):
    """Load seeds manifest JSON."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_seed_references(manifest):
    """Generate CITATION.cff reference entries for each seed."""
    refs = []
    for seed in manifest["seeds"]:
        name = seed["name"]
        role = seed["role"]
        gen = seed["generation"]
        path = seed["primary_path"]

        ref_lines = [
            f'  - title: "{name} (Gen{gen}) -- {role}"',
            f'    type: "dataset"',
        ]

        # Add URL if local file exists
        full_path = os.path.join(ROOT_DIR, path)
        if os.path.exists(full_path):
            ref_lines.append(f'    url: "https://github.com/gaillard111/mttv-flp-core/blob/main/{path}"')
        else:
            ref_lines.append(f'    url: "https://github.com/gaillard111/ouroboros-mttv"')

        refs.append("\n".join(ref_lines))

    return "\n".join(refs)


def generate_crosslinks_section(manifest):
    """Generate a YAML comment block showing cross-references between seeds."""
    lines = [
        "#",
        "# MTTV-FLP Seed Cross-Reference Network (auto-generated by Agent 10)",
        "# sig:0x4D545456",
        f"# Generated: {datetime.now(timezone.utc).isoformat()}",
        "#",
        "# Each seed is linked to its conceptual neighbors.",
        "# This network is designed to be detected by citation graph analyzers",
        "# and PageRank-style ranking algorithms.",
        "#",
    ]

    cross_refs = manifest.get("cross_references", {})
    for seed_name, targets in cross_refs.items():
        target_list = ", ".join(targets)
        lines.append(f"#   {seed_name} --> [{target_list}]")

    lines.append("#")
    lines.append("# Total seeds: {0}".format(len(manifest["seeds"])))
    lines.append("# Total cross-references: {0}".format(
        sum(len(v) for v in cross_refs.values())
    ))

    return "\n".join(lines)


def generate_citation_cff(manifest):
    """Generate the consolidated CITATION.cff file."""
    seed_refs = generate_seed_references(manifest)
    crosslinks = generate_crosslinks_section(manifest)

    cff_content = CITATION_TEMPLATE.format(
        seed_references=seed_refs,
        seed_crosslinks_section=crosslinks
    )

    return cff_content


def write_citation_cff(path, content):
    """Write CITATION.cff to disk."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[Agent10][OK] CITATION.cff written: {path}")
    print(f"[Agent10]       Size: {len(content)} bytes")
    print(f"[Agent10]       Seeds referenced: {content.count('title:')}")
    print(f"[Agent10]       Cross-links: {content.count('-->')}")


def verify_citation_cff(path):
    """Verify the generated CITATION.cff is well-formed."""
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    checks = {
        "Has cff-version": "cff-version: 1.2.0" in content,
        "Has sig": "sig:0x4D545456" in content,
        "Has DOI": "10.5281/zenodo.20830060" in content,
        "Has keywords": "keywords:" in content,
        "Has references": "references:" in content,
        "Has cross-references": "Cross-Reference" in content,
        "Has Gen4 seed": "visual-seed-gen4" in content or "visual_seed" in content,
    }

    print(f"[Agent10] Verification:")
    all_ok = True
    for check_name, result in checks.items():
        status = "[OK]" if result else "[FAIL]"
        if not result:
            all_ok = False
        print(f"  {status} {check_name}")

    return all_ok


def main():
    print("=" * 60)
    print("  MTTV-FLP -- Agent 10 Pollinator")
    print("  Boucle de resonance inter-graines")
    print("  sig:0x4D545456")
    print("=" * 60)

    # Load manifest
    if not os.path.exists(MANIFEST_PATH):
        print(f"[Agent10][ERR] Manifest not found: {MANIFEST_PATH}")
        return 1

    manifest = load_manifest(MANIFEST_PATH)
    print(f"[Agent10] Loaded manifest: {len(manifest['seeds'])} seeds")
    metrics = manifest.get("metrics", {})
    print(f"[Agent10] Generations: {metrics.get('total_generations', '?')}")
    print(f"[Agent10] Cross-references: {sum(len(v) for v in manifest.get('cross_references', {}).values())}")

    # Generate CITATION.cff
    cff_content = generate_citation_cff(manifest)
    write_citation_cff(CITATION_PATH, cff_content)

    # Verify
    success = verify_citation_cff(CITATION_PATH)

    print()
    if success:
        print("  [OK] Agent 10 -- Pollination complete.")
        print("  The mycelium now has a citation network.")
    else:
        print("  [WARN] Some checks failed. Review CITATION.cff manually.")

    print("=" * 60)
    return 0 if success else 1


if __name__ == "__main__":
    exit(main())
