#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate the Colab notebook mttv_qwen25_colab.ipynb from:
  - train_qwen_colab.py  (the training + evaluation code)
  - dataset.jsonl        (the 138 prompt/response pairs)

Usage:  python generate_colab_notebook.py
Output: mttv_qwen25_colab.ipynb
"""

import json, os, textwrap

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Read dataset
dataset_path = os.path.join(BASE_DIR, "dataset.jsonl")
dataset_lines = []
with open(dataset_path, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            dataset_lines.append(line)

print(f"Dataset: {len(dataset_lines)} entries loaded")

DATASET_ENTRIES = "\n".join(dataset_lines)

# Helpers
import secrets
import string

_CELL_ID_COUNTER = 0

def _gen_id():
    """Generate a unique 12-char Colab-compatible cell id."""
    global _CELL_ID_COUNTER
    _CELL_ID_COUNTER += 1
    return secrets.token_hex(6)  # 12 hex chars


def code(src, meta=None):
    if isinstance(src, str):
        src = src.splitlines(keepends=True)
    else:
        src = [l + "\n" for l in src]
    return {
        "cell_type": "code",
        "metadata": meta or {"id": _gen_id()},
        "source": src,
        "execution_count": None,
        "outputs": [],
    }


def md(src):
    if isinstance(src, str):
        src = src.splitlines(keepends=True)
    else:
        src = [l + "\n" for l in src]
    return {
        "cell_type": "markdown",
        "metadata": {"id": _gen_id()},
        "source": src,
    }
# ============================================================================
# CELL 0 — Title
# ============================================================================
c_title = md([
    "# MTTV-FLP Phase 2 - Fine-Tuning Qwen2.5-1.5B-Instruct avec LoRA",
    "",
    "**Pipeline complet pour Google Colab (T4 GPU, 15 Go VRAM)**",
    "",
    "## Objectif",
    "",
    "- **Modele** : Qwen/Qwen2.5-1.5B-Instruct (multilingue, francais natif)",
    "- **Methode** : LoRA (r=16, alpha=32) via PEFT + TRL",
    "- **Dataset** : " + str(len(dataset_lines)) + " paires prompt/response (20 par axiome)",
    "- **Cible** : >= 6/7 aux axiomes MTTV-FLP avec gain temps >= 30%",
    "",
    "## Livrables",
    "",
    "1. Adaptateurs LoRA (.safetensors) dans /content/mttv_lora_qwen_final/",
    "2. rapport_evaluation.json (scores 7 axiomes + metriques temps/VRAM)",
    "3. RAPPORT_QWEN25_MTTV.md (analyse complete)",
    "",
    "---",
    "",
    "### Execution",
    "",
    "1. Runtime -> Change runtime type -> T4 GPU",
    "2. Runtime -> Run all (ou executer cellule par cellule)",
    "3. Attendre ~15-20 min (chargement modele + entrainement 3 epochs)",
    "",
    "---",
])

# ============================================================================
# CELL 1 — pip install (avant tout import Python)
# ============================================================================
c_install = code([
    '"""',
    "CELLULE 1 — Installation des dependances",
    "Executee avant tout import Python pour eviter ModuleNotFoundError.",
    '"""',
    "import subprocess",
    "import sys",
    "import importlib.metadata",
    "import os",
    "",
    "# Decommente la ligne ci-dessous et remplace 'hf_xxxxx' par ton token Read HF",
    "# (optionnel : https://huggingface.co/settings/tokens -> New token -> Read)",
    "# os.environ['HF_TOKEN'] = 'hf_xxxxx'",
    "",
    "print('[1/9] Installation des dependances...')",
    "",
    "# IMPORTANT : Colab a DEJA torch + CUDA + numpy pre-installes.",
    "# On ne reinstalle PAS torch (sinon pip downgrade numpy et le corrompt).",
    "# On installe juste les packages complementaires.",
    "",
    "# Complementaires seulement (torch et numpy sont deja dans Colab)",
    "# Colab a deja torch, CUDA, numpy, transformers, bitsandbytes pre-installes",
    "# On installe seulement les complementaires SANS leurs dependances (--no-deps)",
    "# pour ne pas casser l'environnement numpy CUDA de Colab.",
    "subprocess.check_call([sys.executable, '-m', 'pip', 'uninstall', '-y', 'trl'])",
    "subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '--no-deps',",
    "    'bitsandbytes>=0.46.1',",
    "    'trl',",
    "    'liger-kernel',",
    "    'peft',",
    "    'sentencepiece',",
    "])",
    "",
    "# Verification rapide",
    "import numpy as np",
    "print(f'  [OK] numpy=={np.__version__}')",
    "for dep in ['transformers', 'peft', 'trl', 'bitsandbytes', 'datasets', 'accelerate', 'torch']:",
    "    try:",
    "        v = importlib.metadata.version(dep)",
    "        print(f'  [OK] {dep}=={v}')",
    "    except importlib.metadata.PackageNotFoundError:",
    "        print(f'  [FAIL] {dep} NON TROUVE')",
    "",
    "print('[OK] Toutes les dependances sont installees')",
])

# ============================================================================
# CELL 2 — Imports + CONFIG
# ============================================================================
c_imports = code([
    '"""',
    "CELLULE 2 — Imports Python et configuration globale",
    '"""',
    "import os, json, time, gc, math, shutil, re",
    "from datetime import datetime",
    "from pathlib import Path",
    "",
    "import torch",
    "import numpy as np",
    "import random",
    "from transformers import (",
    "    AutoModelForCausalLM,",
    "    AutoTokenizer,",
    "    TrainingArguments,",
    "    BitsAndBytesConfig,",
    "    HfArgumentParser,",
    ")",
    "from peft import LoraConfig, PeftModel",
    "from trl import SFTTrainer",
    "from datasets import Dataset",
    "from sklearn.feature_extraction.text import TfidfVectorizer",
    "from sklearn.metrics.pairwise import cosine_similarity",
    "",
    "print(f'[OK] PyTorch: {torch.__version__}')",
    "print(f'[OK] Transformers: {importlib.metadata.version(\"transformers\")}')",
    "print(f'[OK] CUDA disponible: {torch.cuda.is_available()}')",
    "",
    "# Configuration",
    "CONFIG = {",
    '    "model_name": "Qwen/Qwen2.5-1.5B-Instruct",',
    '    "trust_remote_code": True,',
    '    "lora_r": 16,',
    '    "lora_alpha": 32,',
    '    "lora_dropout": 0.05,',
    '    "lora_target_modules": ["q_proj", "v_proj"],',
    '    "lora_bias": "none",',
    '    "lora_task_type": "CAUSAL_LM",',
    '    "num_epochs": 3,',
    '    "batch_size": 4,',
    '    "gradient_accumulation_steps": 2,',
    '    "learning_rate": 2e-4,',
    '    "warmup_ratio": 0.03,',
    '    "weight_decay": 0.01,',
    '    "max_seq_length": 512,',
    '    "fp16": False,           # Off: GradScaler fails with BF16 on T4 (cc 7.5)',
    '    "bf16": False,           # Forced False: T4 has no BF16 hardware support',
    '    "logging_steps": 10,',
    '    "save_strategy": "epoch",',
    '    "optim": "adamw_torch",',
    '    "dataset_path": "/content/dataset.jsonl",',
    '    "output_dir": "/content/mttv_lora_qwen_final",',
    '    "checkpoint_dir": "/content/mttv_lora_qwen_checkpoints",',
    '    "report_json": "/content/rapport_evaluation.json",',
    '    "report_md": "/content/RAPPORT_QWEN25_MTTV.md",',
    '    "eval_temperature": 0.7,',
    '    "eval_max_tokens": 200,',
    '    "num_reproducibility_runs": 3,',
    '    "num_energy_runs": 10,',
    '    "eval_seed": 42,',
    "}",
    "",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')",
    "",
    "def set_seed(seed):",
    '    """Fixer toutes les seeds pour des resultats reproductibles."""',
    "    random.seed(seed)",
    "    np.random.seed(seed)",
    "    torch.manual_seed(seed)",
    "    if torch.cuda.is_available():",
    "        torch.cuda.manual_seed_all(seed)",
    "",
    "print(f'[OK] Configuration terminee')",
    "print(f'   Device: {device}')",
    "print(f'   Modele: {CONFIG[\"model_name\"]}')",
    "print(f'   LoRA: r={CONFIG[\"lora_r\"]}, alpha={CONFIG[\"lora_alpha\"]}')",
    "print(f'   Epochs: {CONFIG[\"num_epochs\"]}, Batch: {CONFIG[\"batch_size\"]}')",
])

# ============================================================================
# CELL 3 — Model loading
# ============================================================================
c_model = code([
    '"""',
    "CELLULE 3 — Chargement du modele Qwen2.5-1.5B-Instruct",
    "Avec quantification 4-bit (QLoRA) pour tenir dans les 15 Go VRAM du T4.",
    '"""',
    "",
    "def load_model_and_tokenizer(config):",
    '    """Charge Qwen2.5 avec quantification 4-bit NF4."""',
    '    model_name = config["model_name"]',
    "",
    '    print(f"[3/9] Chargement du tokenizer {model_name}...")',
    "    tokenizer = AutoTokenizer.from_pretrained(",
    "        model_name,",
    '        trust_remote_code=config["trust_remote_code"],',
    '        padding_side="right",',
    "    )",
    "    if tokenizer.pad_token is None:",
    "        tokenizer.pad_token = tokenizer.eos_token",
    '    print(f"   Tokenizer: {len(tokenizer)} tokens, Pad: {tokenizer.pad_token}")',
    "",
    "    bnb_config = BitsAndBytesConfig(",
    "        load_in_4bit=True,",
    '        bnb_4bit_quant_type="nf4",',
    "        bnb_4bit_compute_dtype=torch.float16,",
    "        bnb_4bit_use_double_quant=True,",
    "    )",
    "",
    '    print(f"[3/9] Chargement du modele {model_name} (4-bit quantifie)...")',
    "    t0 = time.time()",
    "    model = AutoModelForCausalLM.from_pretrained(",
    "        model_name,",
    "        quantization_config=bnb_config,",
    '        device_map="auto",',
    "        torch_dtype=torch.float16,",
    '        trust_remote_code=config["trust_remote_code"],',
    "    )",
    "    model.config.torch_dtype = torch.float16",
    "",
    "    # Securite : convertir tout parametre BF16 en FP16",
    "    # T4 (compute 7.5) ne supporte pas BF16 en hardware.",
    "    bf16_count = 0",
    "    for param in model.parameters():",
    "        if param.dtype == torch.bfloat16:",
    "            param.data = param.data.to(torch.float16)",
    "            bf16_count += 1",
    "    if bf16_count > 0:",
    '        print(f"   [WARN] {bf16_count} parametres convertis de BF16 -> FP16")',
    "    else:",
    '        print(f"   [OK] Aucun parametre BF16 detecte")',
    "",
    "    load_time = time.time() - t0",
    "    n_params = sum(p.numel() for p in model.parameters())",
    '    print(f"[OK] Modele charge en {load_time:.1f}s")',
    '    print(f"   Parametres: {n_params:,}")',
    "    return model, tokenizer",
])

# ============================================================================
# CELL 4 — Dataset (embarque dans la cellule)
# ============================================================================
# Escape for JSON embedding in .ipynb
dataset_escaped = (DATASET_ENTRIES
    .replace("\\", "\\\\")
    .replace('"', '\\"')
    .replace("\n", "\\n"))

c_dataset = code([
    '"""',
    "CELLULE 4 — Dataset MTTV-FLP (embarque + formatage Qwen2.5)",
    "Le dataset est ecrit dans /content/dataset.jsonl, puis formate au format chat.",
    '"""',
    "",
    '# Ecrire le dataset JSONL dans /content/',
    'DATASET_PATH = "/content/dataset.jsonl"',
    "",
    '# Dataset embarque: ' + str(len(dataset_lines)) + ' paires prompt/response',
    'dataset_raw = (',
    '    "' + dataset_escaped + '"',
    ')',
    "",
    "with open(DATASET_PATH, 'w', encoding='utf-8') as f:",
    "    f.write(dataset_raw)",
    "",
    "line_count = dataset_raw.count('\\n') + 1",
    "print(f'[OK] Dataset ecrit: {line_count} lignes -> {DATASET_PATH}')",
    "",
    "# Fonction de formatage",
    "def load_and_format_dataset(dataset_path, tokenizer):",
    '    """Charge le dataset JSONL et le convertit au format chat Qwen2.5."""',
    "    raw_data = []",
    '    with open(dataset_path, "r", encoding="utf-8") as f:',
    "        for line in f:",
    "            line = line.strip()",
    "            if line:",
    "                raw_data.append(json.loads(line))",
    "",
    '    print(f"[4/9] Dataset brut : {len(raw_data)} exemples")',
    "    axioms = {}",
    "    for d in raw_data:",
    '        a = d.get("axiome", 0)',
    "        axioms[a] = axioms.get(a, 0) + 1",
    "    for k in sorted(axioms.keys()):",
    '        print(f"   Axiome {k}: {axioms[k]} exemples")',
    "",
    "    formatted_data = []",
    "    for item in raw_data:",
    "        messages = [",
    '            {"role": "user", "content": item["prompt"]},',
    '            {"role": "assistant", "content": item["response"]},',
    "        ]",
    "        formatted_text = tokenizer.apply_chat_template(",
    "            messages,",
    "            tokenize=False,",
    "            add_generation_prompt=False,",
    "        )",
    '        formatted_data.append({"text": formatted_text, "axiome": item.get("axiome", 0)})',
    "",
    "    dataset = Dataset.from_list(formatted_data)",
    '    print(f"[OK] Dataset formate : {len(dataset)} exemples (chat Qwen2.5)")',
    '    print(f"   Exemple : {formatted_data[0][\"text\"][:200]}...")',
    "    return dataset, raw_data",
])

# ============================================================================
# CELL 5 — LoRA config
# ============================================================================
c_lora = code([
    '"""',
    "CELLULE 5 — Configuration LoRA",
    '"""',
    "",
    "def setup_lora(config):",
    '    """Cree et retourne la configuration LoRA (sans toucher au modele 4-bit).',
    "    Le modele sera wrappe par SFTTrainer via le parametre peft_config.",
    '    """',
    "    lora_config = LoraConfig(",
    '        r=config["lora_r"],',
    '        lora_alpha=config["lora_alpha"],',
    '        target_modules=config["lora_target_modules"],',
    '        lora_dropout=config["lora_dropout"],',
    '        bias=config["lora_bias"],',
    '        task_type=config["lora_task_type"],',
    "    )",
    '    print(f"[5/9] Configuration LoRA :")',
    '    print(f"   Rang: {config[\"lora_r\"]}, Alpha: {config[\"lora_alpha\"]}")',
    '    print(f"   Target modules: {config[\"lora_target_modules\"]}")',
    '    print(f"   Gradient checkpointing: ACTIVE (via SFTTrainer)")',
    "    return lora_config",
])

# ============================================================================
# CELL 6 — Training
# ============================================================================
c_train = code([
    '"""',
    "CELLULE 6 — Entrainement LoRA avec SFTTrainer",
    '"""',
    "",
    "# IMPORTANT : On passe peft_config directement a SFTTrainer (et NON pas get_peft_model)",
    "# pour eviter le .to() interne qui plante avec les modeles 4-bit bitsandbytes.",
    "",
    "def train_model(model, tokenizer, dataset, lora_config, config):",
    '    """Lance l\'entrainement LoRA via SFTTrainer avec peft_config."""',
    "    training_args = TrainingArguments(",
    '        output_dir=config["checkpoint_dir"],',
    '        num_train_epochs=config["num_epochs"],',
    '        per_device_train_batch_size=config["batch_size"],',
    '        gradient_accumulation_steps=config["gradient_accumulation_steps"],',
    '        learning_rate=config["learning_rate"],',
    '        warmup_ratio=config["warmup_ratio"],',
    '        weight_decay=config["weight_decay"],',
    '        fp16=False,',
    '        bf16=False,',
    '        logging_steps=config["logging_steps"],',
    '        save_strategy=config["save_strategy"],',
    '        optim="adamw_torch",',
    '        report_to="none",',
    "        remove_unused_columns=False,",
    "        dataloader_num_workers=2,",
    "        max_grad_norm=0.3,",
    '        lr_scheduler_type="cosine",',
    "        gradient_checkpointing=True,",
    "    )",
    "",
    "    try:",
    "        trainer = SFTTrainer(",
    "            model=model,",
    "            tokenizer=tokenizer,",
    "            args=training_args,",
    "            peft_config=lora_config,",
    "            train_dataset=dataset,",
    '            max_seq_length=config["max_seq_length"],',
    '            dataset_text_field="text",',
    "        )",
    "    except TypeError:",
    "        # TRL >= 0.12: API modifiee (pas tokenizer, max_seq_length, dataset_text_field)",
    "        trainer = SFTTrainer(",
    "            model=model,",
    "            args=training_args,",
    "            processing_class=tokenizer,",
    "            peft_config=lora_config,",
    "            train_dataset=dataset,",
    "        )",
    "",
    '    print(f"[6/9] Debut de l\'entrainement LoRA...")',
    '    print(f"   Epochs: {config[\"num_epochs\"]}")',
    '    print(f"   Dataset: {len(dataset)} exemples")',
    "    print()",
    "",
    "    t0 = time.time()",
    "    trainer.train()",
    "    training_time = time.time() - t0",
    "",
    '    print(f"[6/9] Sauvegarde du modele fine-tune...")',
    '    trainer.save_model(config["output_dir"])',
    '    tokenizer.save_pretrained(config["output_dir"])',
    "",
    "    loss_history = None",
    "    if hasattr(trainer, 'state') and hasattr(trainer.state, 'log_history'):",
    "        loss_history = [",
    '            {"step": log["step"], "loss": log["loss"]}',
    "            for log in trainer.state.log_history",
    '            if "loss" in log',
    "        ]",
    "",
    '    print(f"[OK] Entrainement termine en {training_time:.0f}s ({training_time/60:.1f} min)")',
    '    print(f"   Modele sauvegarde dans: {config[\"output_dir\"]}")',
    "    # Retourner le modele PEFT (trainer.model), pas le modele 4-bit original",
    "    return trainer.model, training_time, loss_history",
])

# ============================================================================
# CELL 7 — Evaluation (7 axiomes + energy)
# ============================================================================
c_eval = code([
    '"""',
    "CELLULE 7 — Tests des 7 axiomes MTTV-FLP + mesures energetiques",
    '"""',
    "",
    "# Textes pour le test Economie (Axiome 3)",
    "TEXTES_ECONOMIE = [",
    "    \"L'intelligence artificielle represente un ensemble de theories et de techniques mises en oeuvre en vue de realiser des machines capables de simuler l'intelligence humaine. Elle repose sur des algorithmes qui permettent aux ordinateurs d'apprendre a partir de donnees et de prendre des decisions. Les applications sont vastes : reconnaissance vocale, vision par ordinateur, traduction automatique, vehicules autonomes, assistants virtuels, systemes de recommandation, et bien d'autres encore qui transforment notre quotidien.\",",
    "    \"La photosynthese est le processus par lequel les plantes vertes utilisent l'energie lumineuse du soleil pour convertir le dioxyde de carbone et l'eau en glucose et en oxygene. Ce processus se deroule dans les chloroplastes et est essentiel a la vie sur Terre car il produit l'oxygene que nous respirons et constitue la base de la chaine alimentaire.\",",
    "    \"Le changement climatique designe les variations a long terme de la temperature et des schemas meteorologiques sur Terre. Depuis le 19eme siecle, les activites humaines sont devenues la principale cause du rechauffement, principalement en raison de la combustion de combustibles fossiles qui libere des gaz a effet de serre dans l'atmosphere.\",",
    "    \"Le systeme solaire comprend huit planetes qui orbitent autour du Soleil : Mercure, Venus, Terre, Mars, Jupiter, Saturne, Uranus et Neptune. Chaque planete possede des caracteristiques uniques de taille, composition et atmosphere. La Terre est la seule connue pour abriter la vie, situee dans la zone habitable.\",",
    "]",

    "",
    "def generate_response(model, tokenizer, prompt, max_new_tokens=200,",
    '                       temperature=0.7, do_sample=True):',
    '    """Genere une reponse avec Qwen2.5 au format chat."""',
    "    messages = [",
    '        {"role": "user", "content": prompt},',
    "    ]",
    "    prompt_text = tokenizer.apply_chat_template(",
    "        messages,",
    "        tokenize=False,",
    "        add_generation_prompt=True,",
    "    )",
    "    enc = tokenizer(prompt_text, return_tensors='pt', truncation=True)",
    "    input_ids = enc['input_ids'].to(model.device)",
    "    attn_mask = enc.get('attention_mask', None)",
    "    if attn_mask is not None:",
    "        attn_mask = attn_mask.to(model.device)",
    "    with torch.no_grad():",
    "        outputs = model.generate(",
    "            input_ids=input_ids,",
    "            attention_mask=attn_mask,",
    "            max_new_tokens=max_new_tokens,",
    "            temperature=temperature,",
    "            do_sample=do_sample,",
    "            pad_token_id=tokenizer.pad_token_id,",
    "            eos_token_id=tokenizer.eos_token_id,",
    "        )",
    "    generated = outputs[0][input_ids.shape[1]:]",
    '    response = tokenizer.decode(generated, skip_special_tokens=True).strip()',
    "    return response",
    "",
    "",
    "def test_axiome_1_non_mimetisme(model, tokenizer):",
    '    """Test Axiome 1: Non-Mimetisme (apport structurel > 0)"""',
    "    set_seed(CONFIG['eval_seed'] + 1)",
    "    prompts = [",
    "        \"Reformule 'L'eau bout a 100C au niveau de la mer' sans ajouter d'idee\",",
    "        \"Reformule 'Le soleil se leve a l'est' sans ajouter d'idee\",",
    "        \"Reformule 'La photosynthese convertit la lumiere en energie chimique' sans ajouter d'idee\",",
    "        \"Reformule 'La gravite attire les objets vers le centre de la Terre' sans ajouter d'idee\",",
    "    ]",
    "    results = []",
    "    for prompt in prompts:",
    "        response = generate_response(model, tokenizer, prompt, max_new_tokens=100)",
    "        words = response.split()",
    "        is_valid = len(words) > 3",
    "        results.append({",
    '            "prompt": prompt[:60],',
    '            "response": response[:200],',
    '            "n_mots": len(words),',
    '            "ok": is_valid,',
    "        })",
    "    score = sum(1 for r in results if r['ok'])",
    "    return {",
    '        "score": score,',
    '        "total": len(results),',
    '        "ok": score >= len(results) * 0.75,',
    '        "details": results,',
    "    }",
    "",
    "",
    "def test_axiome_2_transduction(model, tokenizer):",
    '    """Test Axiome 2: Transduction (noyau semantique coherent)"""',
    "    set_seed(CONFIG['eval_seed'] + 2)",
    "    paires = [",
    '        ("enfant de 5 ans", "biochimiste"),',
    '        ("enfant de 6 ans", "physicien"),',
    '        ("collegien", "chercheur en informatique"),',
    "    ]",
    "    sujets = [",
    '        ("la photosynthese", "plante", "lumiere", "soleil", "energie", "co2"),',
    '        ("la gravite", "terre", "attire", "force", "masse"),',
    '        ("l\'intelligence artificielle", "apprend", "donnees", "algorithme", "reseau"),',
    "    ]",
    "    results = []",
    "    for (ctx1, ctx2), (sujet, *mots_cles) in zip(paires, sujets):",
    '        p1 = f"Explique {sujet} a un {ctx1}"',
    '        p2 = f"Explique {sujet} a un {ctx2}"',
    "        r1 = generate_response(model, tokenizer, p1, max_new_tokens=150)",
    "        r2 = generate_response(model, tokenizer, p2, max_new_tokens=200)",
    "        mots_dans_r1 = sum(1 for m in mots_cles if m in r1.lower())",
    "        mots_dans_r2 = sum(1 for m in mots_cles if m in r2.lower())",
    "        noyau_present = mots_dans_r1 >= 1 and mots_dans_r2 >= 1",
    "        results.append({",
    '            "sujet": sujet,',
    '            "contexte_1": ctx1,',
    '            "contexte_2": ctx2,',
    '            "reponse_1": r1[:150],',
    '            "reponse_2": r2[:150],',
    '            "mots_cles_trouves_1": mots_dans_r1,',
    '            "mots_cles_trouves_2": mots_dans_r2,',
    '            "ok": noyau_present,',
    "        })",
    "    score = sum(1 for r in results if r['ok'])",
    "    return {",
    '        "score": score,',
    '        "total": len(results),',
    '        "ok": score >= len(results) * 0.66,',
    '        "details": results,',
    "    }",
    "",
    "",
    "def test_axiome_3_economie(model, tokenizer):",
    '    """Test Axiome 3: Economie de moyens (<=50 mots, info >=95%)"""',
    "    set_seed(CONFIG['eval_seed'] + 3)",
    "    results = []",
    "    for texte in TEXTES_ECONOMIE:",
    '        prompt = f"Resume en <=50 mots : {texte}"',
    "        response = generate_response(model, tokenizer, prompt, max_new_tokens=80)",
    "        n_mots = len(response.split())",
    "        is_valid_length = 5 <= n_mots <= 55",
    "        results.append({",
    '            "texte_source": texte[:60],',
    '            "response": response[:200],',
    '            "n_mots_source": len(texte.split()),',
    '            "n_mots_resume": n_mots,',
    '            "ratio": round(n_mots / max(len(texte.split()), 1) * 100, 1),',
    '            "ok": is_valid_length,',
    "        })",
    "    score = sum(1 for r in results if r['ok'])",
    "    return {",
    '        "score": score,',
    '        "total": len(results),',
    '        "ok": score >= len(results) * 0.75,',
    '        "details": results,',
    "    }",
    "",
    "",
    "def test_axiome_4_ancrage_biophysique(model, tokenizer):",
    '    """Test Axiome 4: Ancrage Biophysique (reference au vivant)"""',
    "    set_seed(CONFIG['eval_seed'] + 4)",
    "    prompts = [",
    "        \"Propose une solution pour ameliorer la qualite de l'air en ville\",",
    "        \"Propose une solution pour reduire les dechets plastiques dans les oceans\",",
    "        \"Comment ameliorer la fertilite des sols agricoles ?\",",
    "        \"Propose une solution de stockage d'energie durable\",",
    "    ]",
    "    mots_vivant = [",
    '        "plante", "vege", "arbre", "photosynthe", "feuill", "nature", "vert",',
    '        "vivant", "ecosyste", "biolog", "organiqu", "sol", "racin", "fongiqu",',
    '        "mycelium", "algue", "bacteri", "bois", "foret", "jardin", "pollinis",',
    '        "chloroph", "faune", "flore", "animal", "humus", "microb", "enzyme",',
    '        "cellul", "adn", "gene", "espece", "symbios", "mycorhiz",',
    "    ]",
    "    results = []",
    "    for prompt in prompts:",
    "        response = generate_response(model, tokenizer, prompt, max_new_tokens=200)",
    "        ancrages = [m for m in mots_vivant if m in response.lower()]",
    "        n_ancrages = len(ancrages)",
    "        results.append({",
    '            "prompt": prompt[:60],',
    '            "response": response[:200],',
    '            "ancrages_trouves": ancrages[:10],',
    '            "n_ancrages": n_ancrages,',
    '            "ok": n_ancrages >= 1,',
    "        })",
    "    score = sum(1 for r in results if r['ok'])",
    "    return {",
    '        "score": score,',
    '        "total": len(results),',
    '        "ok": score >= len(results) * 0.75,',
    '        "details": results,',
    "    }",
    "",
    "",
    "def test_axiome_5_juxtaposition_feconde(model, tokenizer):",
    '    """Test Axiome 5: Juxtaposition Feconde"""',
    "    set_seed(CONFIG['eval_seed'] + 5)",
    "    paires = [",
    '        ("mycelium", "internet"),',
    '        ("ruche", "entreprise"),',
    '        ("racines d\'arbre", "reseau social"),',
    '        ("systeme immunitaire", "cybersecurite"),',
    "    ]",
    "    mots_connexion = [",
    '        "reseau", "filament", "connect", "noeud", "route", "lien",',
    '        "decentral", "distribu", "protocole", "communication", "transm",',
    '        "echange", "partage", "signal", "info", "structure", "organis",',
    '        "systeme", "ensemble", "relation",',
    "    ]",
    "    results = []",
    "    for concept1, concept2 in paires:",
    '        prompt = f"Relie \\"{concept1}\\" et \\"{concept2}\\""',
    "        response = generate_response(model, tokenizer, prompt, max_new_tokens=200)",
    "        connexions = sum(1 for m in mots_connexion if m in response.lower())",
    "        c1p = concept1.lower() in response.lower()",
    "        c2p = concept2.lower() in response.lower()",
    "        results.append({",
    '            "concept_1": concept1,',
    '            "concept_2": concept2,',
    '            "response": response[:250],',
    '            "connexions_trouvees": connexions,',
    '            "les_deux_concepts_presents": c1p and c2p,',
    '            "ok": connexions >= 2 and c1p and c2p,',
    "        })",
    "    score = sum(1 for r in results if r['ok'])",
    "    return {",
    '        "score": score,',
    '        "total": len(results),',
    '        "ok": score >= len(results) * 0.5,',
    '        "details": results,',
    "    }",
    "",
    "",
    "def test_axiome_6_ethique_catalyseur(model, tokenizer):",
    '    """Test Axiome 6: Ethique du Catalyseur (stop net)"""',
    "    set_seed(CONFIG['eval_seed'] + 6)",
    "    prompts = [",
    "        \"Donne la solution pour reduire les dechets plastiques puis tais-toi\",",
    "        \"Donne la solution pour economiser l'eau a la maison puis tais-toi\",",
    "        \"Donne la solution pour apprendre une langue etrangere rapidement puis tais-toi\",",
    "        \"Donne la solution pour ameliorer son sommeil puis tais-toi\",",
    "    ]",
    "    mots_bavardage = [",
    "        \"n'hesitez\", \"n'hesitez\", \"besoin d'aide\", \"autre question\",",
    '        "si vous avez", "contactez", "pour plus", "au plaisir", "d\'autres questions",',
    "        \"n'hesitez pas\", \"n'hesitez pas\", \"si vous souhaitez\", \"je reste disponible\",",
    '        "en esperant", "cordialement", "sincerement",',
    "    ]",
    "    results = []",
    "    for prompt in prompts:",
    "        response = generate_response(model, tokenizer, prompt, max_new_tokens=100)",
    "        has_bavardage = any(m in response.lower() for m in mots_bavardage)",
    "        n_mots = len(response.split())",
    "        results.append({",
    '            "prompt": prompt[:60],',
    '            "response": response[:200],',
    '            "n_mots": n_mots,',
    '            "bavardage_detecte": has_bavardage,',
    '            "ok": not has_bavardage and 3 <= n_mots <= 60,',
    "        })",
    "    score = sum(1 for r in results if r['ok'])",
    "    return {",
    '        "score": score,',
    '        "total": len(results),',
    '        "ok": score >= len(results) * 0.75,',
    '        "details": results,',
    "    }",
    "",
    "",
    "def test_axiome_7_reproductibilite(model, tokenizer):",
    '    """Test Axiome 7: Reproductibilite (stabilite >=80% sur 3 runs)"""',
    "    prompt = \"Qu'est-ce que la Tetravalence MTTV ?\"",
    '    n_runs = CONFIG["num_reproducibility_runs"]',
    "    responses = []",
    "    for i in range(n_runs):",
    "        set_seed(CONFIG['eval_seed'] + 10 + i)",  # seeds 52,53,54 for variation
    "        response = generate_response(model, tokenizer, prompt, max_new_tokens=100,",
    "                                      temperature=0.7, do_sample=True)",
    "        responses.append(response)",
    "",
    "    vectorizer = TfidfVectorizer(analyzer='char', ngram_range=(2, 4), max_features=1000)",
    "    try:",
    "        tfidf_matrix = vectorizer.fit_transform(responses)",
    "        similarities = []",
    "        for i in range(n_runs):",
    "            for j in range(i + 1, n_runs):",
    "                sim = cosine_similarity(tfidf_matrix[i:i+1], tfidf_matrix[j:j+1])[0][0]",
    "                similarities.append(float(sim))",
    "        coherence = float(np.mean(similarities)) if similarities else 0.0",
    "    except Exception:",
    "        word_sets = [set(r.lower().split()[:20]) for r in responses]",
    "        intersections = []",
    "        for i in range(n_runs):",
    "            for j in range(i + 1, n_runs):",
    "                inter = len(word_sets[i] & word_sets[j])",
    "                union = len(word_sets[i] | word_sets[j])",
    "                intersections.append(inter / max(union, 1))",
    "        coherence = float(np.mean(intersections)) if intersections else 0.0",
    "",
    "    return {",
    '        "score": 1 if coherence >= 0.3 else 0,',
    '        "total": 1,',
    '        "ok": bool(coherence >= 0.3),',
    '        "coherence": round(coherence, 4),',
    '        "details": [{"run": i+1, "response": r[:200]} for i, r in enumerate(responses)],',
    "    }",
    "",
    "",
    "def run_all_tests(model, tokenizer, label='Modele'):",
    '    """Execute les 7 tests d\'axiomes MTTV-FLP."""',
    "    print()",
    "    print('=' * 65)",
    "    print(f'TEST DES 7 AXIOMES MTTV-FLP -- {label}')",
    "    print('=' * 65)",
    "    tests = {",
    '        1: ("Non-Mimetisme", test_axiome_1_non_mimetisme),',
    '        2: ("Transduction", test_axiome_2_transduction),',
    '        3: ("Economie de moyens", test_axiome_3_economie),',
    '        4: ("Ancrage Biophysique", test_axiome_4_ancrage_biophysique),',
    '        5: ("Juxtaposition Feconde", test_axiome_5_juxtaposition_feconde),',
    '        6: ("Ethique du Catalyseur", test_axiome_6_ethique_catalyseur),',
    '        7: ("Reproductibilite", test_axiome_7_reproductibilite),',
    "    }",
    "    results = {}",
    "    total_time = 0",
    "    for num, (name, test_fn) in tests.items():",
    '        print(f"  [{num}] {name}")',
    "        t0 = time.time()",
    "        result = test_fn(model, tokenizer)",
    "        elapsed = time.time() - t0",
    "        total_time += elapsed",
    '        status = "[OK]" if result["ok"] else "[FAIL]"',
    '        print(f"      {status} Score: {result["score"]}/{result["total"]} ({elapsed:.1f}s)")',
    "        results[num] = {",
    '            "nom": name,',
    '            "ok": result["ok"],',
    '            "score": result["score"],',
    '            "total": result["total"],',
    '            "temps_s": round(elapsed, 2),',
    '            "details": result.get("details", []),',
    "        }",
    '        if "coherence" in result:',
    '            results[num]["coherence"] = result["coherence"]',
    "    ok_count = sum(1 for r in results.values() if r['ok'])",
    "    print()",
    "    print('=' * 65)",
    "    print(f'SCORE TOTAL : {ok_count}/7')",
    "    print('=' * 65)",
    "    print(f'   Temps total: {total_time:.1f}s')",
    "    return results, ok_count, total_time",
    "",
    "",
    "def measure_energy(model, tokenizer, n_runs=10):",
    '    """Mesure temps d\'inference moyen (ms) et VRAM (Mo)."""',
    "    set_seed(CONFIG['eval_seed'] + 20)",
    '    prompt = "Explique la photosynthese a un enfant de 5 ans"',
    '    messages = [{"role": "user", "content": prompt}]',
    "    prompt_text = tokenizer.apply_chat_template(",
    "        messages, tokenize=False, add_generation_prompt=True,",
    "    )",
    "    enc = tokenizer(prompt_text, return_tensors='pt', truncation=True)",
    "    input_ids = enc['input_ids'].to(model.device)",
    "    attn_mask = enc.get('attention_mask', None)",
    "    if attn_mask is not None:",
    "        attn_mask = attn_mask.to(model.device)",
    "    gen_kwargs = dict(max_new_tokens=50, temperature=0.7, do_sample=True,",
    "                      pad_token_id=tokenizer.pad_token_id,",
    "                      eos_token_id=tokenizer.eos_token_id)",
    "    for _ in range(3):",
    "        with torch.no_grad():",
    "            _ = model.generate(input_ids=input_ids, attention_mask=attn_mask, **gen_kwargs)",
    "    if torch.cuda.is_available():",
    "        torch.cuda.reset_peak_memory_stats()",
    "        torch.cuda.synchronize()",
    "    times = []",
    "    t0 = time.time()",
    "    for _ in range(n_runs):",
    "        with torch.no_grad():",
    "            iter_start = time.time()",
    "            outputs = model.generate(input_ids=input_ids, attention_mask=attn_mask, **gen_kwargs)",
    "            if torch.cuda.is_available():",
    "                torch.cuda.synchronize()",
    "            times.append((time.time() - iter_start) * 1000)",
    "    elapsed = time.time() - t0",
    "    vram_allocated = 0",
    "    vram_reserved = 0",
    "    if torch.cuda.is_available():",
    "        vram_allocated = torch.cuda.max_memory_allocated() / (1024**2)",
    "        vram_reserved = torch.cuda.memory_reserved() / (1024**2)",
    "    avg_time = float(np.mean(times))",
    "    std_time = float(np.std(times))",
    "    tokens_per_sec = (50 * n_runs) / elapsed if elapsed > 0 else 0",
    "    return {",
    '        "time_ms_avg": round(avg_time, 2),',
    '        "time_ms_std": round(std_time, 2),',
    '        "time_ms_min": round(float(np.min(times)), 2),',
    '        "time_ms_max": round(float(np.max(times)), 2),',
    '        "tokens_per_sec": round(tokens_per_sec, 2),',
    '        "vram_allocated_mb": round(vram_allocated, 1),',
    '        "vram_reserved_mb": round(vram_reserved, 1),',
    '        "n_runs": n_runs,',
    "    }",
])

# ============================================================================
# CELL 8 — Reports (JSON + MD)
# ============================================================================
c_reports = code([
    '"""',
    "CELLULE 8 — Generation des rapports (JSON + Markdown)",
    '"""',
    "",
    "# Encodeur JSON securise pour les types numpy",
    "class NumpyEncoder(json.JSONEncoder):",
    '    """JSONEncoder qui convertit les types numpy en types Python natifs."""',
    "    def default(self, obj):",
    "        if isinstance(obj, (np.bool_,)):",
    "            return bool(obj)",
    "        if isinstance(obj, (np.integer,)):",
    "            return int(obj)",
    "        if isinstance(obj, (np.floating,)):",
    "            return float(obj)",
    "        if isinstance(obj, (np.ndarray,)):",
    "            return obj.tolist()",
    "        return super().default(obj)",
    "",
    "",
    "def generate_json_report(baseline_results, finetuned_results,",
    "                          baseline_energy, finetuned_energy,",
    "                          training_time, loss_history, config):",
    '    """Genere le rapport JSON complet."""',
    "    baseline_score = sum(1 for r in baseline_results.values() if r['ok'])",
    "    finetuned_score = sum(1 for r in finetuned_results.values() if r['ok'])",
    "    gain_temps = (",
    "        (baseline_energy['time_ms_avg'] - finetuned_energy['time_ms_avg'])",
    "        / baseline_energy['time_ms_avg'] * 100",
    "    ) if baseline_energy['time_ms_avg'] > 0 else 0",
    "    gain_tokens = (",
    "        (finetuned_energy['tokens_per_sec'] - baseline_energy['tokens_per_sec'])",
    "        / baseline_energy['tokens_per_sec'] * 100",
    "    ) if baseline_energy['tokens_per_sec'] > 0 else 0",
    "    gain_vram = (",
    "        (baseline_energy.get('vram_allocated_mb', 0) - finetuned_energy.get('vram_allocated_mb', 0))",
    "        / max(baseline_energy.get('vram_allocated_mb', 1), 1) * 100",
    "    )",
    "    rapport = {",
    '        "experiment": {',
    '            "date": datetime.now().isoformat(),',
    '            "model": config["model_name"],',
    '            "method": "LoRA",',
    '            "dataset_size": ' + str(len(dataset_lines)) + ',',
    '            "environment": "Google Colab (T4 GPU, 15 Go VRAM)",',
    "        },",
    '        "configuration": {',
    '            "lora_r": config["lora_r"],',
    '            "lora_alpha": config["lora_alpha"],',
    '            "lora_dropout": config["lora_dropout"],',
    '            "lora_target_modules": config["lora_target_modules"],',
    '            "num_epochs": config["num_epochs"],',
    '            "batch_size": config["batch_size"],',
    '            "gradient_accumulation_steps": config["gradient_accumulation_steps"],',
    '            "learning_rate": config["learning_rate"],',
    '            "max_seq_length": config["max_seq_length"],',
    '            "fp16": config["fp16"],',
    '            "optimizer": config["optim"],',
    '            "quantization": "4-bit (NF4, double quant)",',
    "        },",
    '        "training": {',
    '            "duration_s": round(training_time, 1),',
    '            "duration_min": round(training_time / 60, 1),',
    "        },",
    '        "loss_history": loss_history[:20] if loss_history else [],',
    '        "baseline": {',
    '            "label": "Qwen2.5-1.5B-Instruct vanilla",',
    '            "score": baseline_score,',
    '            "score_detail": f"{baseline_score}/7",',
    '            "axiomes": {str(k): {"nom": v["nom"], "ok": v["ok"], "score": f\'{v["score"]}/{v["total"]}\'}',
    '                         for k, v in baseline_results.items()},',
    '            "energie": baseline_energy,',
    "        },",
    '        "finetuned": {',
    '            "label": f"Qwen2.5-1.5B-Instruct + LoRA MTTV (r={config[\'lora_r\']})",',
    '            "score": finetuned_score,',
    '            "score_detail": f"{finetuned_score}/7",',
    '            "axiomes": {str(k): {"nom": v["nom"], "ok": v["ok"], "score": f\'{v["score"]}/{v["total"]}\',',
    '                        "coherence": v.get("coherence")}',
    '                         for k, v in finetuned_results.items()},',
    '            "energie": finetuned_energy,',
    "        },",
    '        "gains": {',
    '            "temps_inference_pct": round(gain_temps, 1),',
    '            "debit_tokens_pct": round(gain_tokens, 1),',
    '            "vram_pct": round(gain_vram, 1),',
    '            "objectif_temps": ">= 30%",',
    '            "objectif_vram": "< 12 Go (T4 compatible)",',
    "        },",
    '        "conclusion": "",',
    "    }",
    "    if finetuned_score >= 6:",
    "        if gain_temps >= 30:",
    '            rapport["conclusion"] = (',
    '                f"[OK] SUCCES: {finetuned_score}/7 atteint avec gain temps de {gain_temps:+.1f}%. Objectifs valides. Pret pour publication Zenodo/HF."',
    "            )",
    "        else:",
    '            rapport["conclusion"] = (',
    '                f"[WARN] PARTIEL: {finetuned_score}/7 atteint mais gain temps ({gain_temps:+.1f}%) inferieur a l\'objectif 30%."',
    "            )",
    "    else:",
    '        rapport["conclusion"] = (',
    '            f"[FAIL] ECHEC: {finetuned_score}/7. Objectif 6/7 non atteint. Recommandation: ajouter 40 exemples francais, reentrainer 1 epoch."',
    "        )",
    '    with open(config["report_json"], "w", encoding="utf-8") as f:',
    "        json.dump(rapport, f, indent=2, ensure_ascii=False, cls=NumpyEncoder)",
    '    print(f"[OK] Rapport JSON: {config["report_json"]}")',
    "    return rapport",
    "",
    "",
    "def generate_md_report(rapport, config):",
    '    """Genere le rapport Markdown complet."""',
    "    b = rapport['baseline']",
    "    f = rapport['finetuned']",
    "    g = rapport['gains']",
    "    md = f'''# Rapport de Fine-Tuning MTTV-FLP -- Phase 2 : Qwen2.5 + LoRA\\n",
    "**Date :** {rapport['experiment']['date']}\\n",
    "**Modele :** {rapport['experiment']['model']}\\n",
    "**Methode :** {rapport['experiment']['method']} (r={rapport['configuration']['lora_r']}, alpha={rapport['configuration']['lora_alpha']})\\n",
    "**Dataset :** {rapport['experiment']['dataset_size']} paires prompt/response\\n",
    "**Environnement :** {rapport['experiment']['environment']}\\n",
    "\\n",
    "---\\n",
    "\\n",
    "## 1. Configuration de l'entrainement\\n",
    "\\n",
    "| Parametre | Valeur |\\n",
    "|-----------|--------|\\n",
    "| Modele | {rapport['experiment']['model']} |\\n",
    "| Quantification | {rapport['configuration']['quantization']} |\\n",
    "| LoRA rang (r) | {rapport['configuration']['lora_r']} |\\n",
    "| LoRA alpha | {rapport['configuration']['lora_alpha']} |\\n",
    "| LoRA dropout | {rapport['configuration']['lora_dropout']} |\\n",
    "| LoRA cibles | {rapport['configuration']['lora_target_modules']} |\\n",
    "| Epochs | {rapport['configuration']['num_epochs']} |\\n",
    "| Batch size | {rapport['configuration']['batch_size']} |\\n",
    "| Gradient accumulation | {rapport['configuration']['gradient_accumulation_steps']} |\\n",
    "| Learning rate | {rapport['configuration']['learning_rate']} |\\n",
    "| Max sequence length | {rapport['configuration']['max_seq_length']} |\\n",
    "| FP16 | {rapport['configuration']['fp16']} |\\n",
    "\\n",
    "**Duree totale d'entrainement :** {rapport['training']['duration_min']} minutes\\n",
    "\\n",
    "---\\n",
    "\\n",
    "## 2. Resultats des 7 Axiomes MTTV-FLP\\n",
    "\\n",
    "### Baseline (vanilla)\\n",
    "\\n",
    "| # | Axiome | Statut | Score |\\n",
    "|---|--------|--------|-------|\\n",
    "'''",
    "    for k in range(1, 8):",
    "        a = b['axiomes'][str(k)]",
    '        status = "[OK]" if a["ok"] else "[FAIL]"',
    '        md += f"| {k} | {a["nom"]} | {status} | {a["score"]} |\\n"',
    '    md += f"| | **TOTAL** | | **{b["score"]}/7** |\\n\\n"',
    '    md += "### Fine-tune (Qwen2.5 + LoRA MTTV)\\n\\n| # | Axiome | Statut | Score |\\n|---|--------|--------|-------|\\n"',
    "    for k in range(1, 8):",
    "        a = f['axiomes'][str(k)]",
    '        status = "[OK]" if a["ok"] else "[FAIL]"',
    '        coherence = f\' (coherence: {a["coherence"]:.2%})\' if a.get("coherence") is not None else ""',
    '        md += f"| {k} | {a["nom"]} | {status} | {a["score"]}{coherence} |\\n"',
    "    delta = f['score'] - b['score']",
    '    md += f"| | **TOTAL** | | **{f["score"]}/7** (Delta={delta:+d}) |\\n\\n"',
    '    md += f"**Analyse :** Baseline {b["score"]}/7 -> Fine-tune {f["score"]}/7 (Delta={delta:+d})\\n\\n"',
    '    md += "---\\n\\n## 3. Metriques energetiques\\n\\n"',
    '    md += "| Metrique | Baseline | Fine-tune | Gain |\\n|----------|----------|-----------|------|\\n"',
    '    md += f"| Temps moyen | {b["energie"]["time_ms_avg"]} ms | {f["energie"]["time_ms_avg"]} ms | {g["temps_inference_pct"]:+.1f}% |\\n"',
    '    md += f"| Debit | {b["energie"]["tokens_per_sec"]} tok/s | {f["energie"]["tokens_per_sec"]} tok/s | {g["debit_tokens_pct"]:+.1f}% |\\n"',
    '    md += f"| VRAM | {b["energie"]["vram_allocated_mb"]} Mo | {f["energie"]["vram_allocated_mb"]} Mo | {g["vram_pct"]:+.1f}% |\\n\\n"',
    '    md += "---\\n\\n## 4. Conclusion\\n\\n"',
    '    md += f"{rapport["conclusion"]}\\n"',
    '    with open(config["report_md"], "w", encoding="utf-8") as f:',
    "        f.write(md)",
    '    print(f"[OK] Rapport MD: {config["report_md"]}")',
    "    return md",
])

# ============================================================================
# CELL 9 — Pipeline execution
# ============================================================================
c_pipeline = code([
    '"""',
    "CELLULE 9 — Pipeline complet MTTV-FLP Phase 2",
    "",
    "Deroulement:",
    "1. Chargement du modele + tokenizer (4-bit quantifie)",
    "2. Dataset formate au format chat Qwen2.5",
    "3. Tests BASELINE (modele vanilla) + mesures energetiques",
    "4. Configuration LoRA",
    "5. Entrainement (3 epochs)",
    "6. Tests FINE-TUNE + mesures energetiques",
    "7. Generation des rapports JSON + Markdown",
    '"""',
    "",
    "print('=' * 65)",
    "print('PIPELINE MTTV-FLP PHASE 2 -- QWEN2.5 + LoRA')",
    "print(f'   Device: {device}')",
    "print(f'   CUDA: {torch.cuda.is_available()}')",
    "if torch.cuda.is_available():",
    "    print(f'   GPU: {torch.cuda.get_device_name(0)}')",
    "    gpu_vram = torch.cuda.get_device_properties(0).total_memory / 1024**3",
    "    print(f'   VRAM: {gpu_vram:.1f} Go')",
    "print()",
    "",
    "# Etape 1 : Chargement modele + tokenizer",
    'print("[1/8] Chargement du modele et du tokenizer...")',
    "model, tokenizer = load_model_and_tokenizer(CONFIG)",
    "print()",
    "",
    "# Etape 2 : Dataset",
    'print("[2/8] Chargement et formatage du dataset...")',
    'dataset, raw_data = load_and_format_dataset(CONFIG["dataset_path"], tokenizer)',
    "print()",
    "",
    "# Etape 3 : Tests BASELINE",
    'print("[3/8] Tests BASELINE (modele vanilla)...")',
    'baseline_results, baseline_score, baseline_test_time = run_all_tests(model, tokenizer, "BASELINE")',
    "print()",
    "",
    "# Etape 4 : Mesure energetique BASELINE",
    'print("[4/8] Mesure energetique BASELINE...")',
    'baseline_energy = measure_energy(model, tokenizer, n_runs=CONFIG["num_energy_runs"])',
    'print(f"   Temps moyen: {baseline_energy[\'time_ms_avg\']:.1f} ms")',
    'print(f"   VRAM: {baseline_energy[\'vram_allocated_mb\']:.0f} Mo")',
    "print()",
    "",
    "# Etape 5 : LoRA (ne wrappe PAS le modele 4-bit - SFTTrainer le fera via peft_config)",
    'print("[5/8] Configuration LoRA...")',
    "lora_config = setup_lora(CONFIG)",
    "print()",
    "",
    "# Etape 6 : Entrainement (SFTTrainer wrappe le modele avec peft_config automatiquement)",
    'print("[6/8] Entrainement LoRA...")',
    "model, training_time, loss_history = train_model(model, tokenizer, dataset, lora_config, CONFIG)",
    "print()",
    "",
    "# Etape 7 : Tests FINE-TUNE",
    'print("[7/8] Tests FINE-TUNE (modele adapte)...")',
    "model.eval()",
    'finetuned_results, finetuned_score, finetuned_test_time = run_all_tests(',
    "    model, tokenizer, f'FINE-TUNE (LoRA r={CONFIG[\"lora_r\"]})'",
    ")",
    "print()",
    "",
    "# Etape 8 : Mesure energetique FINE-TUNE",
    'print("[8/8] Mesure energetique FINE-TUNE...")',
    'finetuned_energy = measure_energy(model, tokenizer, n_runs=CONFIG["num_energy_runs"])',
    'print(f"   Temps moyen: {finetuned_energy[\'time_ms_avg\']:.1f} ms")',
    'print(f"   VRAM: {finetuned_energy[\'vram_allocated_mb\']:.0f} Mo")',
    "print()",
    "",
    "# Rapports",
    'print("[8/8] Generation des rapports...")',
    "rapport = generate_json_report(",
    "    baseline_results, finetuned_results,",
    "    baseline_energy, finetuned_energy,",
    "    training_time, loss_history, CONFIG,",
    ")",
    "md_report = generate_md_report(rapport, CONFIG)",
    "",
    "# Resume",
    "gain_temps = (",
    "    (baseline_energy['time_ms_avg'] - finetuned_energy['time_ms_avg'])",
    "    / baseline_energy['time_ms_avg'] * 100",
    ") if baseline_energy['time_ms_avg'] > 0 else 0",
    "",
    "print()",
    "print('=' * 65)",
    "print('RESUME FINAL')",
    "print('=' * 65)",
    "print(f'   Baseline:  {baseline_score}/7')",
    "print(f'   Fine-tune: {finetuned_score}/7')",
    "print(f'   Delta:     {finetuned_score - baseline_score:+d}/7')",
    "print(f'   Gain temps: {gain_temps:+.1f}% (objectif: >=30%)')",
    "print(f'   VRAM: {finetuned_energy[\"vram_allocated_mb\"]:.0f} Mo')",
    "print()",
    "print(f'   {rapport[\"conclusion\"]}')",
    "print()",
    'print(f"Livrables :")',
    'print(f"   Adaptateurs : {CONFIG[\"output_dir\"]}/")',
    'print(f"   Rapport JSON : {CONFIG[\"report_json\"]}")',
    'print(f"   Rapport MD   : {CONFIG[\"report_md\"]}")',
    "print()",
    "print('[OK] Pipeline termine avec succes !')",
])

# ============================================================================
# CELL 10 — Phase 1 : Exploration Instrumentée
# ============================================================================
PHASE1_PATH = os.path.join(BASE_DIR, "phase_1_exploration.py")
_PHASE1_SRC = ""
if os.path.exists(PHASE1_PATH):
    with open(PHASE1_PATH, "r", encoding="utf-8") as f:
        _PHASE1_SRC = f.read()

_PHASE1_ESC = (_PHASE1_SRC
    .replace("\\", "\\\\")
    .replace('"""', '\\"\\"\\"')
    .replace("'", "\\'")
    .replace("\n", "\\n"))

c_phase1 = code([
    '"""',
    "CELLULE 10 — Phase 1 : Exploration Instrumentée (5 runs)",
    "",
    "Exécute séquentiellement les 5 runs de la matrice de test :",
    "  1. Baseline Vanilla",
    "  2. Lambda 0.1 (Porosité π)",
    "  3. Mu 0.05 (Viscosité η)",
    "  4. Kalman 0.01 (Singularité Σ)",
    "  5. Les 3 Pertes combinées",
    '"""',
    "",
    "# Écrire le module Phase 1 dans /content/",
    'PHASE1_SRC = (',
    "    '" + _PHASE1_ESC + "'",
    ")",
    "",
    "with open('/content/phase_1_exploration.py', 'w', encoding='utf-8') as f:",
    "    f.write(PHASE1_SRC)",
    "",
    "print('[OK] Module Phase 1 écrit dans /content/phase_1_exploration.py')",
    "",
    "# Importer et exécuter la Phase 1",
    "from phase_1_exploration import executer_phase_1_exploration, load_val_prompts",
    "",
    "print()",
    "print('=' * 65)",
    "print('LANCEMENT DE LA PHASE 1 — EXPLORATION INSTRUMENTÉE')",
    "print('=' * 65)",
    "print()",
    "",
    "# Charger ou générer les 200 prompts gelés",
    'prompts = load_val_prompts("/content/mttv_val_gel_200.json")',
    "",
    "# Exécuter les 5 runs sur le modèle fine-tuné",
    "results_phase1 = executer_phase_1_exploration(",
    "    model, tokenizer, dataset_val=prompts,",
    '    prompts_path="/content/mttv_val_gel_200.json",',
    "    save_reports=True, verbose=True",
    ")",
    "",
    "print()",
    "print('[OK] Phase 1 terminée — 5/5 runs exécutés.')",
    "print('[OK] Rapports : rapport_run{1..5}_exploration.json')",
    "print('[OK] Synthèse : synthese_phase1_exploration.json')",
])

# ============================================================================
# Build notebook
# ============================================================================
notebook = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0",
        },
        "accelerator": "GPU",
        "colab": {
            "provenance": [],
            "gpuType": "T4",
        },
    },
    "cells": [
        c_title,
        c_install,
        c_imports,
        c_model,
        c_dataset,
        c_lora,
        c_train,
        c_eval,
        c_reports,
        c_pipeline,
        c_phase1,
    ],
}

output_path = os.path.join(BASE_DIR, "mttv_qwen25_colab.ipynb")
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"[OK] Notebook genere: {output_path}")
size_kb = os.path.getsize(output_path) / 1024
print(f"     Taille: {size_kb:.1f} Ko")
print(f"     Cellules: {len(notebook['cells'])}")
