# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  gedmo.listener.sluggable:
    class: Gedmo\Sluggable\SluggableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]

  #fos user listeners
  app.form.registration:
    class: ThoughtBundle\Form\RegistrationType
    tags:
      - { name: form.type, alias: app_user_registration }

  acme_user.registration:
    class: ThoughtBundle\EventListener\RegistrationListener
    arguments:
      entityManager: "@doctrine.orm.entity_manager"
      container: "@service_container"
    tags:
      - { name: kernel.event_subscriber}