services:
    thought.admin.topic:
        class: ThoughtBundle\Admin\TopicAdmin
        arguments:
            - ~
            - ThoughtBundle\Entity\Topic
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: Thoughts, label: "Topics" }

    thought.admin.thought:
        class: ThoughtBundle\Admin\ThoughtAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Thoughts, label: "Thoughts" }
        arguments:
            - ~
            - ThoughtBundle\Entity\Thought
            - 'ThoughtBundle:ThoughtAdmin'
    thought.admin.content:
        class: ThoughtBundle\Admin\ContentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: "Content" }
        arguments:
            - ~
            - ThoughtBundle\Entity\Content
            - 'ThoughtBundle:ContentAdmin'

    thought.admin.mail:
        class: ThoughtBundle\Admin\MailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: "Emails" }
        arguments:
        - ~
        - ThoughtBundle\Entity\GeneralMail
        - ~
        calls:
            - method: setMyRootPath
              arguments:
                  - '%kernel.root_dir%'

    thought.admin.dynamicpage:
        class: ThoughtBundle\Admin\DynamicPageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pages, label: "Pages" }
        arguments:
            - ~
            - ThoughtBundle\Entity\DynamicPage
            - ~

    thought.admin.banner:
        class: ThoughtBundle\Admin\BannerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Banners, label: "Banners" }
        arguments:
            - ~
            - ThoughtBundle\Entity\Banner
            - ~


    thought.admin.menu:
        class: ThoughtBundle\Admin\MenuAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Menu, label: "Menu" }
        arguments:
            - ~
            - ThoughtBundle\Entity\MenuItem
            - ~

    thought.admin.author:
        class: ThoughtBundle\Admin\AuthorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Authors, label: "Authors" }
        arguments:
            - ~
            - ThoughtBundle\Entity\Author
            - 'ThoughtBundle:AuthorAdmin'

    thought.recommended_thought:
            class: ThoughtBundle\Service\RecommendedThoughtService
            arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    thought.parser.service:
        class: ThoughtBundle\Parser\Service
        arguments: ["@service_container"]

#    thought.search_provider.thought:
#        class: ThoughtBundle\Provider\ThoughtProvider
#        arguments:
#            - fos_elastica.index.app.thought
#        tags:
#            - { name: fos_elastica.provider, index: app, type: thought }

    thought.model.thought_model:
        class: ThoughtBundle\Model\ThoughtModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    thought.model.author_model:
        class: ThoughtBundle\Model\AuthorModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    thought.model.thoughtChain_model:
        class: ThoughtBundle\Model\ThoughtChainModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    thought.service.KnpMatcher:
        class: ThoughtBundle\Service\KnpMatcher
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }

    thought.service.export:
        class: ThoughtBundle\Service\Export

    thought.service.search_service:
        class: ThoughtBundle\Service\Search
        arguments: ["@service_container"]

    thought.service.mail_service:
        class: ThoughtBundle\Service\Mail
        arguments: ["@service_container"]

    thought.twig_extension:
        class: ThoughtBundle\Twig\AppExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    thought.comment_notifier:
        class: ThoughtBundle\EventListener\CommentNotifier
        arguments: ["@thought.service.mail_service", "@debug.stopwatch"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    thought.like_notifier:
        class: ThoughtBundle\EventListener\LikeNotifier
        arguments: ["@thought.service.mail_service", "@debug.stopwatch"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
