services:
    thoudght.admin.thought:
        class: ThoughtBundle\Admin\ThoughtAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Thoughts, label: "Thoughts" }
        arguments:
            - ~
            - ThoughtBundle\Entity\Thought
            - 'ThoughtBundle:ThoughtAdmin'
    thoudght.admin.content:
        class: ThoughtBundle\Admin\ContentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: "Content" }
        arguments:
            - ~
            - ThoughtBundle\Entity\Content
            - 'ThoughtBundle:ContentAdmin'

    thought.parser.service:
        class: ThoughtBundle\Parser\Service
        arguments: ["@service_container"]

#    thought.search_provider.thought:
#        class: ThoughtBundle\Provider\ThoughtProvider
#        arguments:
#            - fos_elastica.index.app.thought
#        tags:
#            - { name: fos_elastica.provider, index: app, type: thought }

    thought.model.thought_model:
        class: ThoughtBundle\Model\ThoughtModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    thought.service.KnpMatcher:
        class: ThoughtBundle\Service\KnpMatcher
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }

    thought.service.export:
        class: ThoughtBundle\Service\Export

    thought.service.search_service:
        class: ThoughtBundle\Service\Search
        arguments: ["@service_container"]

    thought.twig_extension:
        class: ThoughtBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
