services:
    thought.admin.user:
        class: ThoughtBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: thought, label: "Users" }
        arguments:
            - ~
            - ThoughtBundle\Entity\User
            - 'ThoughtBundle:UserAdmin'

    app.joboard.admin.job:
        class: ThoughtBundle\Admin\ThoughtAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: thought, label: "Thought" }
        arguments:
            - ~
            - ThoughtBundle\Entity\Thought
            - 'ThoughtBundle:ThoughtAdmin'