<?php

namespace ThoughtBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sonata\AdminBundle\Controller\CRUDController as Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Class ThoughtAdminController
 * @package ThoughtBundle\Controller
 */
class ThoughtAdminController extends Controller
{
    /**
     * @return RedirectResponse
     */
    public function publishAction()
    {
        $object = $this->admin->getSubject();

        if (!$object) {
            throw new NotFoundHttpException(sprintf('unable to find the object with id : %s', $object->getId()));
        }

        $publish = $object->getPublished() ? false : true;

        $object->setPublished($publish);

        $this->admin->update($object);

        $this->addFlash('sonata_flash_success', ($object->getPublished() ? 'Published' : 'Unpublished') . ' successfully');

        return new RedirectResponse($this->admin->generateUrl('list', $this->admin->getFilterParameters()));
    }

    /**
     * @inheritdoc
     */
    public function exportAction(Request $request)
    {

        return parent::exportAction($request); // TODO: Change the autogenerated stub

        $this->admin->checkAccess('export');

        $format = $request->get('format');

        if ($format != 'txt') {
            return parent::exportAction($request); // TODO: Change the autogenerated stub
        }

        $allowedExportFormats = (array) $this->admin->getExportFormats();

        if (!in_array($format, $allowedExportFormats)) {
            throw new \RuntimeException(
                sprintf(
                    'Export in format `%s` is not allowed for class: `%s`. Allowed formats are: `%s`',
                    $format,
                    $this->admin->getClass(),
                    implode(', ', $allowedExportFormats)
                )
            );
        }

        $filename = sprintf(
            'export_%s_%s.%s',
            strtolower(substr($this->admin->getClass(), strripos($this->admin->getClass(), '\\') + 1)),
            date('Y_m_d_H_i_s', strtotime('now')),
            $format
        );

        $filters = $request->get('filter');

        if (count($filters)) {
            $where = array();
            $sortBy = isset($filters['_sort_by']) ? $filters['_sort_by'] : null;
            $sortOrder = isset($filters['_sort_order']) ? $filters['_sort_order'] : null;

            var_dump($this->admin->getFilterFields());
        }


        var_dump($filters);
    }
}
