<?php

namespace Application\Sonata\UserBundle\Repository;

use Application\Sonata\UserBundle\Entity\Dialog;
use Doctrine\ORM\EntityRepository;

/**
 * DialogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DialogRepository extends EntityRepository
{
    /**
     * Finds a dialog between two given users
     * @param $users
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findUsersDialog($users)
    {
        $qb = $this->createQueryBuilder('d');
        $qb
            ->select('d')
            ->leftJoin('d.users', 'u')
            ->leftJoin('d.users', 'u1')
            ->where('u.id = :user1_id')
            ->andWhere('u1.id = :user2_id')
            ->setParameters([
                'user1_id' => $users[0],
                'user2_id' => $users[1],
            ])
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findLastMessage($dialog)
    {
        $qb = $this->createQueryBuilder('d');
        $qb
            ->select('d')
//            ->where('d = :dialog')
//            ->setParameter('dialog', $dialog)
//            ->orderBy('d.messages', 'DESC')
//            ->setMaxResults(1)
        ;
//        dump($qb->getQuery()); die;
        return $qb->getQuery()->getResult();
    }
}
