<?php

namespace Application\Sonata\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Sonata\UserBundle\Entity\User;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\QueryBuilder;

/**
 * FriendshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendshipRepository extends EntityRepository
{
    /**
     * @param User $user
     * @return User[]
     */
    public function getMyFriends(User $user)
    {
        return $this->createQueryBuilder('fs')
            ->select('fs, u')
            ->leftJoin('fs.user', 'u')
            ->andWhere('fs.user = :user')
            ->andWhere('fs.accepted = :accepted')
            ->setParameter('user', $user->getId())
            ->setParameter('accepted', true)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param User $user
     * @return User[]
     */
    public function getFriends(User $user)
    {
        return $this->createQueryBuilder('fs')
            ->select('fs')
            ->where('fs.user = :user')
            ->orWhere('fs.friend = :user')
            ->andWhere('fs.accepted = :accepted')
            ->setParameter('user', $user->getId())
            ->setParameter('accepted', true)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param User $user
     * @param User $friend
     * @return mixed
     * @throws NonUniqueResultException
     */
    public function isFriend(User $user, User $friend)
    {
        return $this->isFriendQuery($user, $friend)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param User $user
     * @param User $friend
     * @return QueryBuilder
     */
    private function isFriendQuery(User $user, User $friend)
    {
        return $this->createQueryBuilder('fs')
            ->select('fs')
            ->where('fs.user = :user AND fs.friend = :friend')
            ->orWhere('fs.user = :friend AND fs.friend = :user')
            ->setParameter('user', $user->getId())
            ->setParameter('friend', $friend->getId());
    }

    /**
     * @param User $user
     * @return array
     */
    public function getFriendRequests(User $user)
    {
        return $this->createQueryBuilder('fs')
            ->select('fs')
            ->where('fs.user = :user OR fs.friend = :user')
            ->andWhere('fs.accepted = false')
            ->setParameter('user', $user->getId())
            ->getQuery()
            ->getResult();
    }

    /**
     * @param User $user
     * @return mixed
     * @throws \Doctrine\ORM\Query\QueryException
     */
    public function getCountFriends(User $user)
    {
        return $this->createQueryBuilder('fs')
            ->select('count(fs)')
            ->where('fs.user = :user OR fs.friend = :user')
            ->andWhere('fs.accepted = true')
            ->setParameter('user', $user->getId())
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param User $user
     * @return mixed
     * @throws \Doctrine\ORM\Query\QueryException
     */
    public function getCountFriendRequests(User $user)
    {
        return $this->createQueryBuilder('fs')
            ->select('count(fs)')
            ->where('fs.friend = :user')
            ->andWhere('fs.accepted = false')
            ->setParameter('user', $user->getId())
            ->getQuery()
            ->getSingleScalarResult();
    }
}
