<?php

namespace Application\Sonata\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getMessagesFromDialog($dialogId)
    {
        $qb = $this->createQueryBuilder('m');
        $qb
            ->select('m')
            ->where('m.dialog = :dialog')
            ->setParameter('dialog', $dialogId)
            ->addOrderBy('m.id','DESC')
        ;

        return $qb->getQuery();
    }

    public function getLastMessageFromDialog($dialogId)
    {
        $qb = $this->createQueryBuilder('m');
        $qb
            ->select('m')
            ->where('m.dialog = :dialog')
            ->setParameter('dialog', $dialogId)
            ->addOrderBy('m.id','DESC')
            ->setMaxResults(1)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
