<?php

namespace Application\Sonata\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getMessagesFromDialog($dialogId)
    {
        return $this->createQueryBuilder('m')
            ->select('m')
            ->where('m.dialog = :dialog')
            ->setParameter('dialog', $dialogId)
            ->addOrderBy('m.id','DESC')
            ->getQuery();
    }
}
